test/CDPosition.js

Adding 4 tests to validate behavior  when adding and updating one NFT ID with more then one NFT ID present in NFTID<>CDP mapping

Add cross NFT ID interference tests to CDP

---

.gitignore
.prettierrc
package-lock.json
package.json

Added configuration file for the Prettier code formatter so we have consistent tabs/spaces, semicolons, brackets between files. The .prettierrc is a custom file that is used by the Prettier VS Code plugin. There are a few different implementations, but this is tested to work with the most popular one (20 million+ downloads):
https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode
Other options we can configure in the future:
https://prettier.io/docs/en/options.html

Vs code styles

---

package-lock.json
package.json

@openzeppelin/test-helpers is required to run the tests

fix(deps): add @openzeppelin/test-helpers to devDependencies

---

contracts/ArchToken.sol
contracts/interfaces/IArchToken.sol
test/ArchToken.js

Live review done by: **Yotam**
Added basic interface, contract and tests for Arch Token

added basic ArchToken interface, contract and test

---

contracts/ArchToken.sol
test/ArchToken.js

Forgot to inherit from ERC20Burnable.sol contract

Add burn arch token

---

.github/workflows/BuildAndTest.yml
.solhint.json
README.md
contracts/CDPosition.sol
contracts/Coordinator.sol
package-lock.json
package.json

- Adds OpenZepplin solhint config to help us enforce our styleguide using common standards to start
- Fix lint issues in all files including CDPosition as part of [this task](https://app.asana.com/0/1202150376267654/1202132667080316)
- Require lint to pass in CI before PR can be merged

chore(lint): add solidity linter to help enforce style guide

---

.github/workflows/BuildAndTest.yml
package.json

See https://github.com/thisisarchimedes/Archimedes_Finance/pull/32. These changes were already submitted but accidentally overwritten while resolving merge conflicts on a different PR.

chore(ci): cache npm deps

---

Architecture/LeverageEngine.sol.strawman
contracts/LeverageAllocator.sol
contracts/LeverageEngine.sol
contracts/ParameterStore.sol
contracts/PositionToken.sol
test/ContractTestContext.test.js
test/LeverageAllocator.js
test/LeverageEngine.js
test/ParameterStore.js
test/PositionToken.js

Add base contracts for LeverageEngine and dependencies

---

Architecture/LeverageEngine.sol.strawman
contracts/LeverageEngine.sol
contracts/ParameterStore.sol
test/ContractTestContext.js
test/LeverageEngine.js

LeverageEngine initial structure and tests

---

contracts/ParameterStore.sol
test/ParameterStore.ts

Add calculate Fees and tests 
Notice base branch is not main! 
FOB - @tomerXarchimedes

calculate origination fee

---

contracts/Coordinator.sol
contracts/Exchanger.sol
contracts/LeverageEngine.sol
contracts/VaultOUSD.sol
test/Coordinator.ts
test/LeverageEngine.ts
test/zIntegrationTests.ts

This PR has 
- Fix to use  archimedesDeposit/archimedesRedeem rather then standard methods
- Fix remaining OUSD variable in exchanger 
- Unblock tests
- Add some more integration tests 
I will remove logging as needed before merging

Fix test posts exchange

---

contracts/ParameterStore.sol
test/ParameterStore.ts

- Add events to parameter changes 
- Guard from getting treasury address as zero 
+ test for above

add ParamStore events; misc fixes 

---

contracts/Exchanger.sol
contracts/LeverageEngine.sol
contracts/ParameterStore.sol
contracts/PositionToken.sol
test/Exchanger.ts

Add protection against over borrowing when exchanging lvUSD for 3CRV  

---

contracts/Exchanger.sol
test/Coordinator.ts
test/Zapper.ts

Fix 3.3 finding in audit draft report

lvUSD burned on unwind

---

test/LeverageEngine.ts

Signed-off-by: Julian <julian@archimedesfi.com>
- Pause event tests ensure the Paused and Unpaused events inherited from PausableUpgradable work properly
- Guardian tests ensure the admin can change the guardian role to another address properly

Added pause event and guardian test suites

---

contracts/AccessController.sol
contracts/ArchToken.sol
contracts/Auction.sol
contracts/BasicAccessController.sol
contracts/CDPosition.sol
contracts/Coordinator.sol
contracts/Exchanger.sol
contracts/LeverageEngine.sol
contracts/LvUSDToken.sol
contracts/Mocks/AccessControllerMock.sol
contracts/Mocks/OUSDMockToken.sol
contracts/Mocks/ParamStoreMock.sol
contracts/Mocks/eventMock.sol
contracts/ParameterStore.sol
contracts/PoolManager.sol
contracts/PositionToken.sol
contracts/VaultOUSD.sol
contracts/Zapper.sol
contracts/interfaces/IAuction.sol
contracts/interfaces/ICoordinator.sol
hardhat.config.ts
test/Zapper.ts

- Adds new ZapIn Event to Zapper
- Bumps Solidity Version for all contracts from 0.8.13 to 0.8.17

ZapIn Event and Bump Solidity

---

test/Zapper.ts

Signed-off-by: Julian <julian@archimedesfi.com>

ZapIn Event Test Fix

---

test/Zapper.ts

Signed-off-by: Julian <julian@archimedesfi.com>

Zapper decimal precision fixes

---

contracts/Zapper.sol

Signed-off-by: Julian <julian@archimedesfi.com>

Zapper slippage revert fix

---

hardhat.config.ts
scripts/startAuction.ts

* had to use a workaround to target aws fork (commented)

start auction script
